(export
 signed-integer-native-descriptors
 signed-integer-le-descriptors
 signed-integer-be-descriptors
 signed-integer-descriptors
 unsigned-integer-native-descriptors
 unsigned-integer-le-descriptors
 unsigned-integer-be-descriptors
 unsigned-integer-descriptors
 float-native-descriptors
 float-le-descriptors
 float-be-descriptors
 complex-native-descriptors
 complex-le-descriptors
 complex-be-descriptors
 integer-descriptors
 float-descriptors
 complex-descriptors
 numeric-descriptors
 )
