(define-module (bytestructures guile struct))
(import
 (srfi :1)
 (srfi :9)
 (srfi :11)
 (bytestructures r6 bytevectors)
 (bytestructures guile utils)
 (bytestructures guile base)
 (bytestructures guile bitfields))
(include-from-path "bytestructures/body/struct.scm")
(export bs:struct)
